name: Process az login oidc
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*

jobs:
  az-login-oidc:
    runs-on: [self-hosted, linux]
    environment: jawas

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: false