name: Deploy virtual WAN Connectivity

on:
  workflow_call:
    inputs:
      Subscription_Id:
        required: true
        type: string

jobs:
  deploy-networking:
    runs-on: [self-hosted, linux]

    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          subscription-id: ${{ inputs.Subscription_Id }}
          enable-AzPSSession: true

      - uses: azure/arm-deploy@v1
        name: Create the Resource Group for vWAN
        id: resourceGroupVWan
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ inputs.Subscription_Id }}
          template: ARMtemplates/resourceGroup.json
          parameters: modules/vwanConnectivity/parameters/resourceGroup.parameters.json

      - uses: azure/arm-deploy@v1
        name: Deploy vWAN Connectivity
        id: deployvWan
        with:
          scope: resourcegroup
          region: westeurope
          resourceGroupName: ${{ steps.resourceGroupVWan.outputs.resourceGroupName }}
          template: modules/vwanConnectivity/vwanConnectivity.bicep
          parameters: modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json

      - uses: azure/arm-deploy@v1
        name: Deploy spokeNetworking
        id: deployspokeNetworking
        with:
          scope: resourcegroup
          region: westeurope
          resourceGroupName: ${{ steps.resourceGroupVWan.outputs.resourceGroupName }}
          template: modules/spokeNetworking/spokeNetworking.bicep
          parameters: modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json

      - uses: azure/arm-deploy@v1
        name: Deploy vWan vNet peering
        id: deployvNetPeeringVWan
        with:
          scope: resourcegroup
          region: westeurope
          resourceGroupName: ${{ steps.resourceGroupVWan.outputs.resourceGroupName }}
          template: modules/vnetPeeringVwan/parameters/vnetPeeringVwan.bicep
          parameters: >
            modules/vnetPeeringVwan/vnetPeeringVwan.parameters.all.json
            parVirtualWanHubResourceId="${{ steps.deployvWan.outputs.outHubVirtualNetworkConnectionResourceI }}"
            parRemoteVirtualNetworkResourceId="${{ steps.deployspokeNetworking.outputs.outSpokeVirtualNetworkId }}"
